agent:
    checkforupdates: true
    minimizetotray: true
    runasservice: true
    startwithos: true
collectors:
    intervalseconds: 60
    system:
        cpu: true
        disk: true
        enabled: true
        eventlog: true
        network: false
        ram: true
gui:
    enabled: true
    shownotifications: true
    startminimized: true
host:
    displayname: DESKTOP-H4POJ3T
    location: New York
    tags:
        - production
        - web-server
logging:
    level: info
    logpath: logs/agent.log
    logtofile: true
    maxagedays: 7
    maxbackups: 3
    maxsizemb: 10
server:
    apiendpoint: http://localhost:5000/api
    apikey: 006f18eb990a4e6081db773fabbbb0e13df5387c9ea14f88b5d6a843b9784cf1
    retrycount: 3
    retrydelay: 5
    timeout: 30
services:
    docker:
        containers: []
        enabled: true
    iis:
        apppools: []
        enabled: true
        sites: []
    systemd:
        enabled: false
        units: []
    windows:
        enabled: true
        services: []
